set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/vundle
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
if (match(system("uname -s"), "Darwin") == -1)
    Plugin 'valloric/youcompleteme'
endif
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'MarcWeber/vim-addon-mw-utils'       " required for snipmate
Plugin 'tomtom/tlib_vim'                    " required for snipmate
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'                 " required for snipmate
Plugin 'easymotion/vim-easymotion'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on
filetype plugin indent on
set number
set autoindent smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nowrap

"Show whitespaces
set list

"Colorscheme
colorscheme default
"set background=dark

"Rainbow parentheses
"au VimEnter * RainbowParenthesesToggle
"au Syntax * RainbowParenthesesLoadRound
"au Syntax * RainbowParenthesesLoadSquare
"au Syntax * RainbowParenthesesLoadBraces

"Indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  ctermbg=236
hi IndentGuidesEven ctermbg=233

"let g:NERDTreeDirArrows=0

"Status Line Stuff
hi User1 ctermbg=237 ctermfg=248
set laststatus=2
set statusline=
set statusline+=%1*
set statusline+=%f
set statusline+=%y
set statusline+=\[%{FileSize()}]
set statusline+=%{exists('g:loaded_fugitive')?fugitive#statusline():''}
set statusline+=[Modified:%{strftime(\"\%c\",getftime(expand(\"\%\%\")))}]
set statusline+=%=
set statusline+=[%c,
set statusline+=%l/%L
set statusline+=\ %P]
function! FileSize()
    let bytes = getfsize(expand("%:p"))
    if bytes <= 0
        return ""
    endif
    if bytes < 1024
        return bytes . "B"
    else
        return (bytes/1024) . "KB"
    endif
endfunction

" Metasploit specific
au! BufRead,BufNewFile */metasploit-framework/*.rb setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab shiftround smarttab

" Custom keybindings
nmap \e :NERDTreeToggle<CR>
nmap <F8> :TagbarToggle<CR>
