#!/bin/sh

source $(dirname $0)/panel_config

volume(){
    VOLUME=$(amixer get Master | grep "Mono:" | awk '{print $4}' | tr -d '[]%')
    ACTIVE=$(amixer get Master | grep "Mono:" | awk '{print $6}' | tr -d '[]')
    if [ "$ACTIVE" == "on" ]; then
        if [ $VOLUME -gt 50 ]; then
            ICON="\uf028"
        elif [ $VOLUME -lt 50 ] && [ $VOLUME -gt 0 ]; then
            ICON="\uf027"
        elif [ $VOLUME -eq 0 ]; then
            ICON="\uf026"
        fi
        echo "%{F$BLUE_COLOR A:pulseaudio-ctl mute:}$(printf '%b' $ICON)%{F-} $VOLUME% %{A}"
    else 
        echo "%{F$RED_COLOR A:pulseaudio-ctl mute:}$(printf '%b' $ICON) $VOLUME% %{A F-}"
    fi
}

mpd(){
    STATUS=$(mpc current)
    echo "%{F$BLUE_COLOR A:mpc toggle: A3:mpc stop:}$(printf '%b' "\ue05c")%{F-} $STATUS%{A A}"
}


wifi_ssid(){
    NAME=$(iwconfig wlp9s0 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
    if [ "$NAME" == "off/any" ]; then
        echo "%{F$RED_COLOR}$(printf '%b' "\uf1eb")%{F-} No Wifi"
    else echo "%{F$WIFI_COLOR}$(printf '%b' "\uf1eb")%{F-} $NAME"
    fi
}

battery() {
    BATTERY=$(acpi -b | awk "{print $1}" | sed 's/\([^:]*\): \([^,]*\), \([0-9]*\)%.*/\3/')
    ICONS=(
            "%{Fred}\uf244%{F-}"
            "\uf243"
            "\uf242"
            "\uf241"
            "\uf240"
            "\uf240"
    )
    POWER_STR=$ICONS[$(($BATTERY / 20 + 1))]
    #POWER_STR="$POWER_STR $BATTERY"
    #echo "%{F$BAT_COLOR}$(printf '%b' "\uf240")%{F-} $BATTERY%"
    echo "%{F$BAT_COLOR}%{F-} $POWER_STR $BATTERY%"
}

load_avg() {
    AVGLOAD=$(cut -d " " -f 1-3 /proc/loadavg)
    echo "%{F$BLUE_COLOR}$(printf '%b' "\ue021")%{F-} $AVGLOAD"
}


while :; do
    #echo "S$(mpd)%{r}$(battery) $SEP $(wifi_ssid) $SEP $(volume)  %{B$YELLOW_COLOR}  %{F$WIFI_COLOR}$(printf '%b' "\ue01f") %{F$BACKGROUND_COLOR} $(date +'%A, %b %d')  %{B$FOREGROUND_COLOR} %{F$WIFI_COLOR} $(printf '%b' "\ue016") %{F$BACKGROUND_COLOR} $(date +'%H:%M')  %{B F-}"
    #echo "S%{r}$(battery) $SEP $(wifi_ssid) $SEP %{B$YELLOW_COLOR}  %{F$WIFI_COLOR}$(printf '%b' "\uf1eb") %{F$BACKGROUND_COLOR} $(date +'%D')  %{B$FOREGROUND_COLOR} %{F$WIFI_COLOR} $(printf '%b' "\ue016") %{F$BACKGROUND_COLOR} $(date +'%I:%M%p')  %{B F-}"
    echo "S%{r}$(battery) $SEP $(volume) $SEP $(wifi_ssid) $SEP %{B$YELLOW_COLOR} %{F$WIFI_COLOR}$(printf '%b' "\uf073") %{F$BACKGROUND_COLOR} $(date +'%D')  %{B$FOREGROUND_COLOR} %{F$WIFI_COLOR} $(printf '%b' "\uf017") %{F$BACKGROUND_COLOR} $(date +'%I:%M%p')  %{B F-}"
done
