#
#/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
# Mute terminal bell
xset -b

# Dropbox
dropboxd &

# Wallpaper
nitrogen --restore &

# Use the Windows key for accents
setxkbmap -option compose:lwin
#synergyc --daemon 192.168.1.135
xrdb ~/.Xresources

#exec ck-launch-session openbox-session

xsetroot -cursor_name left_ptr
exec ck-launch-session xmonad
