#
#/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
# Mute terminal bell
xset -b

# Dropbox
dropboxd &

# Wallpaper
nitrogen --restore &

# Use the Windows key for accents
setxkbmap -option compose:lwin
#synergyc --daemon 192.168.1.135
xrdb ~/.Xresources

DEFAULT_SESSION=xmonad

case $1 in
xmonad)
    trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --height 12 --tint 0x000000 --transparent true &
    nm-applet --sm-disable &
    xsetroot -cursor_name left_ptr
    exec ck-launch-session xmonad
    ;;
openbox)
    tint2 &
    exec ck-launch-session openbox-session
    ;;
*)
    xsetroot -cursor_name left_ptr
    exec ck-launch-session xmonad
    ;;

esac
