#!/bin/sh

monitor_config() {
    bspc config $1 $1
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}

desktop_config() {
    bspc config $1 $1
    for M in $(bspc query -D); do
        bspc config -d $M $1 $2
    done
}

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d $i/{I,II,III,IV,V,VI,VII,VIII,IX,X}
        let i++
done
NMON=$i
unset i

#bspc desktop ^1 -n I
#bspc monitor -a II III IV V VI VII IIX IX X
#bspc monitor -p 14 0 0 0
bspc window -w last.manual

desktop_config window_gap               20
desktop_config split_ratio              0.52
#monitor_config border_width             2
monitor_config border_width             0
desktop_config borderless_monocle       true
desktop_config gapless_monocle          true
desktop_config focus_follows_pointer    true
desktop_config auto_alternate           true
#desktop_config focused_border_color     \#F4CFA1
#desktop_config normal_border_color      \#96745C

bspc rule -a Gimp -d Eight --floating
bspc rule -a Skype --floating

/home/chiggins/.config/polybar/launch.sh
compton --config=$HOME/.config/compton/compton.conf
