#!/bin/sh

desktop_config() {
    bspc config $1 $1
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d $i/{I,II,III,IV,V,VI,VII,VIII,IX,X}
        let i++
done
NMON=$i
unset i

#bspc desktop ^1 -n I
#bspc monitor -a II III IV V VI VII IIX IX X
#bspc monitor -p 14 0 0 0
bspc window -w last.manual

desktop_config window_gap       30
bspc config split_ratio         0.52
bspc config border_width        2
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer   true
bspc config auto_alternate      true
bspc config focused_border_color \#F4CFA1
bspc config normal_border_color \#96745C
bspc config top_padding          20

bspc rule -a Gimp -d Eight --floating
bspc rule -a Skype --floating

#/home/chiggins/.dot/random-scripts/panel &
#wkline &
candybar &
