#
#/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
# Mute terminal bell
xset -b

# Dropbox
# dropboxd &

# Use the Windows key for accents
setxkbmap -option compose:lwin
#synergyc --daemon 192.168.1.135
xrdb ~/.Xresources

DEFAULT_SESSION=xmonad

case $1 in
openbox)
    tint2 &
    exec openbox-session
    ;;
xmonad)
    xsetroot -cursor_name left_ptr
    exec xmonad
    ;;
*)
    tint2 &
    exec openbox-session
    ;;

esac

# Wallpaper
nitrogen --restore &


